In [101]:
import tensorflow as tf
import numpy as np

In [8]:
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
2, 3, activation='relu', input_shape=input_shape[1:])

In [92]:
input_shape = (1, 4, 4, 1)
# 1씩 들어있는 1차원 배열을
# 8개 가지고 있는 2차원 배열을
# 8개 가지고 있는 3차원 배열을
# 4개 만든 것
x = tf.math.round(tf.random.normal(input_shape))

print("X shape :", x.shape)
# filter = 2
# kernel size = 3

# filter를 2개 쓰니까 2개의 채널로 출력이 될 것이다.
# kernel size 는 3 이면 (3,3)의 구조이다.
y = tf.keras.layers.Conv2D(
    1, 3, activation='linear', input_shape=input_shape[1:],
    kernel_initializer='one'
)
y(x).shape

X shape : (1, 4, 4, 1)


TensorShape([1, 2, 2, 1])

In [149]:
x = np.round(np.random.rand(4,4,4) * 10)
x

array([[[ 1.,  0.,  5.,  5.],
        [10.,  4.,  9.,  5.],
        [ 8.,  3.,  2.,  4.],
        [ 5.,  1.,  6.,  8.]],

       [[ 6.,  9.,  2.,  8.],
        [ 2.,  8.,  2.,  1.],
        [ 3., 10.,  3.,  4.],
        [ 2.,  6.,  4.,  3.]],

       [[ 4.,  6.,  9.,  7.],
        [ 1.,  6.,  2.,  4.],
        [ 6.,  1.,  4.,  7.],
        [ 7.,  6.,  4.,  7.]],

       [[ 6.,  8.,  7.,  4.],
        [ 5.,  1.,  8.,  7.],
        [ 3.,  0.,  0.,  6.],
        [ 5.,  8.,  9.,  9.]]])

In [152]:
conv_x = x.reshape(4,4,4,1)
conv_x

array([[[[ 1.],
         [ 0.],
         [ 5.],
         [ 5.]],

        [[10.],
         [ 4.],
         [ 9.],
         [ 5.]],

        [[ 8.],
         [ 3.],
         [ 2.],
         [ 4.]],

        [[ 5.],
         [ 1.],
         [ 6.],
         [ 8.]]],


       [[[ 6.],
         [ 9.],
         [ 2.],
         [ 8.]],

        [[ 2.],
         [ 8.],
         [ 2.],
         [ 1.]],

        [[ 3.],
         [10.],
         [ 3.],
         [ 4.]],

        [[ 2.],
         [ 6.],
         [ 4.],
         [ 3.]]],


       [[[ 4.],
         [ 6.],
         [ 9.],
         [ 7.]],

        [[ 1.],
         [ 6.],
         [ 2.],
         [ 4.]],

        [[ 6.],
         [ 1.],
         [ 4.],
         [ 7.]],

        [[ 7.],
         [ 6.],
         [ 4.],
         [ 7.]]],


       [[[ 6.],
         [ 8.],
         [ 7.],
         [ 4.]],

        [[ 5.],
         [ 1.],
         [ 8.],
         [ 7.]],

        [[ 3.],
         [ 0.],
         [ 0.],
         [ 6.]],

    

In [176]:
y = tf.keras.layers.Conv2D(
    2, (3,3), activation='linear', input_shape=conv_x.shape[1:],
    kernel_initializer=tf.keras.initializers.Constant(value=1)
)
y_poling = tf.keras.layers.MaxPooling2D((2,2))
print(y(conv_x).numpy().reshape(4, 2, 2, 2))
print(y_poling(y(conv_x)).numpy())

[[[[42. 42.]
   [37. 37.]]

  [[48. 48.]
   [42. 42.]]]


 [[[45. 45.]
   [47. 47.]]

  [[40. 40.]
   [41. 41.]]]


 [[[39. 39.]
   [46. 46.]]

  [[37. 37.]
   [41. 41.]]]


 [[[38. 38.]
   [41. 41.]]

  [[39. 39.]
   [48. 48.]]]]
[[[[48. 48.]]]


 [[[47. 47.]]]


 [[[46. 46.]]]


 [[[48. 48.]]]]


In [185]:
x = np.round(np.random.rand(4,28,28) * 10)
conv_x = x.reshape(4, 28, 28, 1)

In [214]:
model = tf.keras.models.Sequential()
model.add(
    tf.keras.layers.Conv2D(
        32, (3,3), activation='linear', input_shape=conv_x.shape[1:],
        kernel_initializer=tf.keras.initializers.Constant(value=1)
    )
)
model.add(
    tf.keras.layers.MaxPooling2D((2,2))
)
model.add(
    tf.keras.layers.Conv2D(
        64, (3,3), activation='linear', input_shape=conv_x.shape[1:],
        kernel_initializer=tf.keras.initializers.Constant(value=1)
    )
)
model.add(
    tf.keras.layers.MaxPooling2D((2,2))
)
model.add(
    tf.keras.layers.Conv2D(
        64, (3,3), activation='linear', input_shape=conv_x.shape[1:],
        kernel_initializer=tf.keras.initializers.Constant(value=1)
    )
)
model.add(tf.keras.layers.Flatten())
model.add(
    tf.keras.layers.Dense(64, activation='linear', input_shape=conv_x.shape[1:],
        kernel_initializer=tf.keras.initializers.Constant(value=1))
)

class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                         self.num_outputs])

  def call(self, inputs):
    return tf.round(inputs / 1000000) 

model.add(MyDenseLayer(64))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

model(conv_x)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [154]:
y = tf.keras.layers.Conv2D(
    2, (3,3), activation='linear', input_shape=conv_x.shape[1:],
    kernel_initializer='one'
)
print(y(conv_x).numpy())

[[[[42. 42.]
   [37. 37.]]

  [[48. 48.]
   [42. 42.]]]


 [[[45. 45.]
   [47. 47.]]

  [[40. 40.]
   [41. 41.]]]


 [[[39. 39.]
   [46. 46.]]

  [[37. 37.]
   [41. 41.]]]


 [[[38. 38.]
   [41. 41.]]

  [[39. 39.]
   [48. 48.]]]]


array([[[[7., 7.],
         [7., 7.]],

        [[7., 7.],
         [8., 8.]]],


       [[[3., 3.],
         [4., 4.]],

        [[3., 3.],
         [4., 4.]]],


       [[[3., 3.],
         [2., 2.]],

        [[4., 4.],
         [4., 4.]]],


       [[[7., 7.],
         [6., 6.]],

        [[6., 6.],
         [5., 5.]]]], dtype=float32)

In [93]:
x[0]

<tf.Tensor: shape=(4, 4, 1), dtype=float32, numpy=
array([[[-0.],
        [-1.],
        [-1.],
        [-1.]],

       [[-2.],
        [ 0.],
        [ 1.],
        [-0.]],

       [[-0.],
        [ 1.],
        [ 1.],
        [ 1.]],

       [[-1.],
        [-0.],
        [-1.],
        [ 0.]]], dtype=float32)>

In [131]:
y.get_weights()

[]